sudo: required

services:
  - docker

before_install:
  - docker build -t yosshii001/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run yosshii001/react-test npm test -- --coverage

after_success:
  - docker build -t junichi02/multi-client ./client
  - docker build -t junichi02/multi-nginx ./nginx
  - docker build -t junichi02/multi-server ./server
  - docker build -t junichi02/multi-worker ./worker
  # log in docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take these images and push them to docker hub
  - docker push junichi02/multi-client
  - docker push junichi02/multi-nginx
  - docker push junichi02/multi-server
  - docker push junichi02/multi-worker
